name: User Story
description: Beschreibung einer neuen User Story für UrbanBloom
title: "[USER STORY]: "
labels: ["user-story", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## User Story Template
        Beschreiben Sie eine neue User Story aus Nutzersicht.

  - type: dropdown
    id: domain
    attributes:
      label: Domain
      description: Zu welcher Domain gehört diese User Story?
      options:
        - User / Identity
        - Action / Observation
        - Plant Catalog
        - Location / District
        - Gamification
        - Challenge
        - Notification / Reminder
        - Admin / Analytics
        - Sync / Offline
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: User Story Beschreibung
      description: "Als [Rolle] möchte ich [Funktion], damit [Nutzen]"
      placeholder: "Als Bürger möchte ich meine Begrünungsaktionen erfassen, damit ich Punkte sammeln kann."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Akzeptanzkriterien
      description: Wann ist diese Story erfüllt?
      placeholder: |
        - [ ] Kriterium 1
        - [ ] Kriterium 2
        - [ ] Kriterium 3
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priorität (MoSCoW)
      options:
        - MUST
        - SHOULD
        - COULD
        - WONT
    validations:
      required: true

  - type: input
    id: story-points
    attributes:
      label: Story Points (Schätzung)
      placeholder: "z.B. 3, 5, 8"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Zusätzliche Notizen
      description: Weitere Informationen, Konversationspunkte, technische Details
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## 🤖 KI-Assistenz Hinweise

        **Verwende die spezialisierten GitHub Copilot Agents für diese Story:**

  - type: dropdown
    id: recommended-agents
    attributes:
      label: Empfohlene Agents
      description: Welche AI Agents sollten bei der Umsetzung helfen?
      multiple: true
      options:
        - "@backend-ddd - Domain-Modellierung (Aggregates, Value Objects, Events)"
        - "@backend-business-logic - Use Cases und API-Implementierung"
        - "@mobile-cdd - Flutter Mobile UI (Atomic Design)"
        - "@web-admin-cdd - Flutter Web Admin UI"
        - "@project-manager - Planung und Task-Breakdown"
        - "@documentation - Dokumentation und Diagramme"
    validations:
      required: false

  - type: textarea
    id: prompt-suggestions
    attributes:
      label: Vorgeschlagene Prompts
      description: Hilfreiche Prompts für die Umsetzung (siehe docs/prompts/)
      placeholder: |
        Backend:
        - "Erstelle User Aggregate mit Email Value Object"
        - "Implementiere RegisterUser Use Case mit Event Publishing"

        Frontend:
        - "Erstelle ActionCard Organism mit Bild, Titel, Punkten"
        - "Implementiere ActionListPage mit Riverpod Provider"
      value: |
        **Backend Prompts** (siehe `docs/prompts/backend-prompts.md`):
        - [Aggregate erstellen]
        - [Use Case implementieren]
        - [REST Endpoint hinzufügen]

        **Frontend Prompts** (siehe `docs/prompts/frontend-prompts.md`):
        - [Atom/Molecule/Organism erstellen]
        - [Page mit Riverpod Provider]
        - [Widget Tests schreiben]

        **Workflow Prompts** (siehe `docs/prompts/workflow-prompts.md`):
        - [User Story in Tasks aufteilen]
        - [Changelog generieren]
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ### 📚 Hilfreiche Ressourcen:
        - **AI Environment Guide**: `docs/ai-environment-guide.md`
        - **Prompt Kataloge**: `docs/prompts/`
        - **Backend Instructions**: `.github/instructions/backend-instructions.md`
        - **Frontend Mobile**: `.github/instructions/frontend-mobile-instructions.md`
        - **Frontend Web**: `.github/instructions/frontend-web-instructions.md`
        - **OpenAPI Spec**: `openapi/urbanbloom-api-v1.yaml`
        - **Domain Model**: `shared-resources/documentation/domain-model-description-urbanbloom.md`

        **Workflow-Tipp**: Starte mit `@project-manager` um die Story in Subtasks aufzuteilen!
