// Mocks generated by Mockito 5.4.6 from annotations
// in school_library_mobile/test/features/user/presentation/pages/registration_screen_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:school_library_mobile/core/network/models/email_availability.dart'
    as _i3;
import 'package:school_library_mobile/core/network/models/registration_request.dart'
    as _i8;
import 'package:school_library_mobile/core/network/models/registration_response.dart'
    as _i2;
import 'package:school_library_mobile/core/network/user_service.dart' as _i6;
import 'package:school_library_mobile/models/auth_tokens.dart' as _i4;
import 'package:school_library_mobile/models/user_profile.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRegistrationResponse_0 extends _i1.SmartFake
    implements _i2.RegistrationResponse {
  _FakeRegistrationResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmailAvailability_1 extends _i1.SmartFake
    implements _i3.EmailAvailability {
  _FakeEmailAvailability_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthTokens_2 extends _i1.SmartFake implements _i4.AuthTokens {
  _FakeAuthTokens_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfile_3 extends _i1.SmartFake implements _i5.UserProfile {
  _FakeUserProfile_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i6.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.RegistrationResponse> register(
    _i8.RegistrationRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i7.Future<_i2.RegistrationResponse>.value(
              _FakeRegistrationResponse_0(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i7.Future<_i2.RegistrationResponse>);

  @override
  _i7.Future<_i3.EmailAvailability> checkEmailAvailability(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmailAvailability, [email]),
            returnValue: _i7.Future<_i3.EmailAvailability>.value(
              _FakeEmailAvailability_1(
                this,
                Invocation.method(#checkEmailAvailability, [email]),
              ),
            ),
          )
          as _i7.Future<_i3.EmailAvailability>);

  @override
  _i7.Future<_i4.AuthTokens> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i7.Future<_i4.AuthTokens>.value(
              _FakeAuthTokens_2(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i7.Future<_i4.AuthTokens>);

  @override
  _i7.Future<_i5.UserProfile> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i7.Future<_i5.UserProfile>.value(
              _FakeUserProfile_3(this, Invocation.method(#getUserProfile, [])),
            ),
          )
          as _i7.Future<_i5.UserProfile>);

  @override
  _i7.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
